export const featuredJobs = [
  {
    id: 1,
    title: " Senior UI Designer",
    company: "Microsoft",
    companyLogo: "/assets/microsoft.png",
    brief: "Design and implement user interfaces for web applications.",
    location: "Lagos, Nigeria",
    mode: "Full-time",
    salary: "₦400K",
    time: "Monthly",
  },
  {
    id: 2,
    title: "Senior Software Engineer",
    company: "Google",
    companyLogo: "/assets/google.png",
    brief: "Develop and maintain scalable web applications.",
    location: "Abuja, Nigeria",
    mode: "Part-time",
    salary: "₦300K",
    time: "Monthly",
  },
  {
    id: 3,
    title: "Product Manager",
    company: "Amazon",
    companyLogo: "/assets/amazon.png",
    brief: "Lead product development and strategy.",
    location: "Remote",
    mode: "Contract",
    salary: "₦500K",
    time: "Monthly",
  },
  {
    id: 4,
    title: "Data Analyst",
    company: "Facebook",
    companyLogo: "/assets/facebook.png",
    brief: "Analyze data to drive business decisions.",
    location: "Lagos, Nigeria",
    mode: "Internship",
    salary: "₦200K",
    time: "Monthly",
  },
  {
    id: 5,
    title: "Marketing Specialist",
    company: "Twitter",
    companyLogo: "/assets/twitter.avif",
    brief: "Develop and execute marketing strategies.",
    location: "Remote",
    mode: "Freelance",
    salary: "₦350K",
    time: "Monthly",
  },
  {
    id: 6,
    title: "UX Researcher",
    company: "LinkedIn",
    companyLogo: "/assets/linkedin.png",
    brief: "Conduct user research to inform design decisions.",
    location: "Abuja, Nigeria",
    mode: "Full-time",
    salary: "₦450K",
    time: "Monthly",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "IBM",
    companyLogo: "/assets/ibm.webp",
    brief: "Manage and optimize cloud infrastructure.",
    location: "Remote",
    mode: "Part-time",
    salary: "₦400K",
    time: "Monthly",
  },
  {
    id: 8,
    title: "Content Writer",
    company: "Adobe",
    companyLogo: "/assets/adobe.png",
    brief: "Create and edit content for various platforms.",
    location: "Lagos, Nigeria",
    mode: "Internship",
    salary: "₦250K",
    time: "Monthly",
  },
  {
    id: 9,
    title: "Sales Executive",
    company: "Salesforce",
    companyLogo: "/assets/salesforce.png",
    brief: "Drive sales and build client relationships.",
    location: "Remote",
    mode: "Freelance",
    salary: "₦300K",
    time: "Monthly",
  },
  {
    id: 10,
    title: "Graphic Designer",
    company: "Canva",
    companyLogo: "/assets/canva.png",
    brief: "Create visual content for marketing and branding.",
    location: "Abuja, Nigeria",
    mode: "Full-time",
    salary: "₦350K",
    time: "Monthly",
  },
];

export const featuredCandidates = [
  {
    id: 1,
    role: "Chartered Accountant",
    name: "Adebayo Ohiri",
    brief: "Experienced in financial analysis and reporting.",
    location: "Lekki, Lagos",
    qualification: "ICAN Certified",
    avatar: "/assets/adebayo.avif",
  },
  {
    id: 2,
    role: "Software Engineer",
    name: "Chinonso Okeke",
    brief: "Proficient in JavaScript and Python.",
    location: "Victoria Island, Lagos",
    qualification: "BSc Computer Science",
    avatar: "/assets/chinonso.avif",
  },
  {
    id: 3,
    role: "Digital Marketer",
    name: "Fatima Bello",
    brief: "Expert in SEO and content marketing.",
    location: "Ikeja, Lagos",
    qualification: "Google Certified",
    avatar: "/assets/fatima.avif",
  },
  {
    id: 4,
    role: "Data Scientist",
    name: "Emeka Nwosu",
    brief: "Skilled in machine learning and data analysis.",
    location: "Abuja, Nigeria",
    qualification: "MSc Data Science",
    avatar: "/assets/emeka.avif",
  },
  {
    id: 5,
    role: "UX/UI Designer",
    name: "Tolu Adebayo",
    brief: "Passionate about user-centered design.",
    location: "Port Harcourt, Nigeria",
    qualification: "BSc Graphic Design",
    avatar: "/assets/tolu.avif",
  },
  {
    id: 6,
    role: "Project Manager",
    name: "Sarah Johnson",
    brief: "Experienced in Agile project management.",
    location: "Remote",
    qualification: "PMP Certified",
    avatar: "/assets/sarah.avif",
  },
  {
    id: 7,
    role: "Content Writer",
    name: "John Doe",
    brief: "Creative writer with a knack for storytelling.",
    location: "Lagos, Nigeria",
    qualification: "BA English Literature",
    avatar: "/assets/john.avif",
  },
  {
    id: 8,
    role: "Sales Executive",
    name: "Jane Smith",
    brief: "Proven track record in sales and client relations.",
    location: "Abuja, Nigeria",
    qualification: "BSc Business Administration",
    avatar: "/assets/jane.avif",
  },
  {
    id: 9,
    role: "Graphic Designer",
    name: "Michael Brown",
    brief: "Expert in Adobe Creative Suite.",
    location: "Ikeja, Lagos",
    qualification: "Diploma in Graphic Design",
    avatar: "/assets/michael.avif",
  },
  {
    id: 10,
    role: "Web Developer",
    name: "Olivia Williams",
    brief: "Full-stack developer with a passion for coding.",
    location: "Remote",
    qualification: "BSc Software Engineering",
    avatar: "/assets/olivia.avif",
  },
];
