export const featuredJobs = [
  {
    id: 1,
    title: " Senior UI Designer",
    company: "Microsoft",
    companyLogo: "/assets/microsoft.png",
    brief: "Design and implement user interfaces for web applications.",
    location: "Lagos, Nigeria",
    mode: "Full-time",
    salary: "₦400K",
    time: "Monthly",
  },
  {
    id: 2,
    title: "Senior Software Engineer",
    company: "Google",
    companyLogo: "/assets/google.png",
    brief: "Develop and maintain scalable web applications.",
    location: "Abuja, Nigeria",
    mode: "Part-time",
    salary: "₦300K",
    time: "Monthly",
  },
  {
    id: 3,
    title: "Product Manager",
    company: "Amazon",
    companyLogo: "/assets/amazon.png",
    brief: "Lead product development and strategy.",
    location: "Remote",
    mode: "Contract",
    salary: "₦500K",
    time: "Monthly",
  },
  {
    id: 4,
    title: "Data Analyst",
    company: "Facebook",
    companyLogo: "/assets/facebook.png",
    brief: "Analyze data to drive business decisions.",
    location: "Lagos, Nigeria",
    mode: "Internship",
    salary: "₦200K",
    time: "Monthly",
  },
  {
    id: 5,
    title: "Marketing Specialist",
    company: "Twitter",
    companyLogo: "/assets/twitter.avif",
    brief: "Develop and execute marketing strategies.",
    location: "Remote",
    mode: "Freelance",
    salary: "₦350K",
    time: "Monthly",
  },
  {
    id: 6,
    title: "UX Researcher",
    company: "LinkedIn",
    companyLogo: "/assets/linkedin.png",
    brief: "Conduct user research to inform design decisions.",
    location: "Abuja, Nigeria",
    mode: "Full-time",
    salary: "₦450K",
    time: "Monthly",
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "IBM",
    companyLogo: "/assets/ibm.webp",
    brief: "Manage and optimize cloud infrastructure.",
    location: "Remote",
    mode: "Part-time",
    salary: "₦400K",
    time: "Monthly",
  },
  {
    id: 8,
    title: "Content Writer",
    company: "Adobe",
    companyLogo: "/assets/adobe.png",
    brief: "Create and edit content for various platforms.",
    location: "Lagos, Nigeria",
    mode: "Internship",
    salary: "₦250K",
    time: "Monthly",
  },
  {
    id: 9,
    title: "Sales Executive",
    company: "Salesforce",
    companyLogo: "/assets/salesforce.png",
    brief: "Drive sales and build client relationships.",
    location: "Remote",
    mode: "Freelance",
    salary: "₦300K",
    time: "Monthly",
  },
  {
    id: 10,
    title: "Graphic Designer",
    company: "Canva",
    companyLogo: "/assets/canva.png",
    brief: "Create visual content for marketing and branding.",
    location: "Abuja, Nigeria",
    mode: "Full-time",
    salary: "₦350K",
    time: "Monthly",
  },
];
